apiVersion: v1
kind: Service
metadata:
  name: account-mysql-db-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: account-mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: order-mysql-db-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: order-mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: stock-mysql-db-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: http
  selector:
    app: stock-mysql-db
