apiVersion: v1
kind: Service
metadata:
  name: order-mysql-db-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: order-mysql-db
---
apiVersion: v1
kind: Service
metadata:
  name: acct-mysql-db-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3306
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: acct-mysql-db
