apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  account-db-password: {{ .Values.database.accountUserInfo.password }}
  order-db-password: {{ .Values.database.orderUserInfo.password }}
  stock-db-password: {{ .Values.database.stockUserInfo.password }}
